/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.example.model.tables.Phones;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PhonesRecord extends UpdatableRecordImpl<PhonesRecord> implements Record3<Long, String, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phones.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phones.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.phones.number</code>.
     */
    public void setNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phones.number</code>.
     */
    public String getNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.phones.client_id</code>.
     */
    public void setClientId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.phones.client_id</code>.
     */
    public Long getClientId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, String, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, String, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Phones.PHONES.ID;
    }

    @Override
    public Field<String> field2() {
        return Phones.PHONES.NUMBER;
    }

    @Override
    public Field<Long> field3() {
        return Phones.PHONES.CLIENT_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getNumber();
    }

    @Override
    public Long component3() {
        return getClientId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getNumber();
    }

    @Override
    public Long value3() {
        return getClientId();
    }

    @Override
    public PhonesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PhonesRecord value2(String value) {
        setNumber(value);
        return this;
    }

    @Override
    public PhonesRecord value3(Long value) {
        setClientId(value);
        return this;
    }

    @Override
    public PhonesRecord values(Long value1, String value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhonesRecord
     */
    public PhonesRecord() {
        super(Phones.PHONES);
    }

    /**
     * Create a detached, initialised PhonesRecord
     */
    public PhonesRecord(Long id, String number, Long clientId) {
        super(Phones.PHONES);

        setId(id);
        setNumber(number);
        setClientId(clientId);
        resetChangedOnNotNull();
    }
}
