/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.model;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.example.model.tables.Addresses;
import org.jooq.example.model.tables.Clients;
import org.jooq.example.model.tables.FlywaySchemaHistory;
import org.jooq.example.model.tables.Phones;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.addresses</code>.
     */
    public final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>public.clients</code>.
     */
    public final Clients CLIENTS = Clients.CLIENTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.phones</code>.
     */
    public final Phones PHONES = Phones.PHONES;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Addresses.ADDRESSES,
            Clients.CLIENTS,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Phones.PHONES
        );
    }
}
