/*
 * This file is generated by jOOQ.
 */
package org.jooq.example.model;


import org.jooq.example.model.tables.Addresses;
import org.jooq.example.model.tables.Clients;
import org.jooq.example.model.tables.FlywaySchemaHistory;
import org.jooq.example.model.tables.Phones;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.addresses</code>.
     */
    public static final Addresses ADDRESSES = Addresses.ADDRESSES;

    /**
     * The table <code>public.clients</code>.
     */
    public static final Clients CLIENTS = Clients.CLIENTS;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.phones</code>.
     */
    public static final Phones PHONES = Phones.PHONES;
}
